VIRUS_LEN = 1000
ANTIGENS_PER_VIRUS = 3
ANTIGEN_LEN = 200
EPITOPES_PER_ANTIGEN = 10
NUM_ANTIBODIES = 100
HAM_DIST = 0.1
#Percent of antibodies to keep and mutate at each time step
ANTIBODY_CLONE_PCT = 0.05
VIRUS_MUTATION_PCT = 0.2
NUM_VIRUS_VARIANTS = 5
