VIRUS_LEN = 1000
ANTIGENS_PER_VIRUS = 1
ANTIGEN_LEN = 200
EPITOPES_PER_ANTIGEN = 10
NUM_ANTIBODIES = 100
HAM_DIST = 0.2

#Percent of antibodies to keep and mutate at each time step
ANTIBODY_CLONE_PCT = 0.2
